name: hqclass
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  splashscreen: ^1.2.0
  flare_flutter: ^2.0.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  url_launcher: ^6.0.3
  carousel_slider: ^2.2.1
  scrollable_positioned_list: ^0.1.7
  cupertino_icons: ^1.0.2
  provider: ^4.3.2+2
  http: ^0.13.3
  shared_preferences: ^2.0.5
  flushbar: ^1.10.4
  flutter_svg: ^0.19.1
  fluttertoast: ^3.1.0
  flutter_slidable: ^0.5.7
  intl: ">=0.15.0 <1.0.0"
  sqflite: ^1.1.6+4
  path_provider: ^2.0.1
  screen_loader: ^2.0.1
  tiengviet: ^0.4.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  local_auth: ^1.1.5
  firebase_analytics: ^8.1.0
  firebase_messaging: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/img/pro-background.png
    - assets/img/onboard-background.png
    - assets/img/logo-android.png
    - assets/img/logo-ios.png
    - assets/img/logo-argon.png
    - assets/img/profile-screen-avatar.jpg
    - assets/img/profile-screen-bg.png
    - assets/img/register-bg.png
    - assets/img/chat-avatar.jpeg
    - assets/img/argon-logo.png
    - assets/img/argon-logo-onboarding.png
    - assets/img/teacher.png
    - assets/img/main_bottom.png
    - assets/img/main_top.png
    - assets/icons/facebook.svg
    - assets/icons/google-plus.svg
    - assets/icons/login.svg
    - assets/icons/signup.svg
    - assets/icons/twitter.svg
    - assets/img/login_bottom.png
    - assets/img/signup_top.png
    - assets/img/chat2.png
    - assets/img/blackboard.png
    - assets/loading.flr
    #    activated
    - assets/global.flr
    #    Bicicleta
    - assets/bicicleta.flr
    #    Untitled
    - assets/Van.flr
    #  Drive
    - assets/car.flr
#    loading idle
    - assets/biker.flr
    - assets/line.png
    - assets/drive-steering-wheel.jpg
    - assets/img/faceID.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600