name: hqclass
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  splashscreen: ^1.2.0
  flare_flutter: ^2.0.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.2
  carousel_slider: ^2.2.1
  scrollable_positioned_list: ^0.1.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider: ^4.3.1
  http: ^0.12.1
  shared_preferences: ^0.5.8
  flushbar: ^1.10.4
  flutter_svg: ^0.19.1
  fluttertoast: ^3.1.0
  flutter_slidable: ^0.5.7
  date_time_picker: "^1.1.1"
  intl: ">=0.15.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/pro-background.png
    - assets/img/onboard-background.png
    - assets/img/logo-android.png
    - assets/img/logo-ios.png
    - assets/img/logo-argon.png
    - assets/img/profile-screen-avatar.jpg
    - assets/img/profile-screen-bg.png
    - assets/img/register-bg.png
    - assets/img/chat-avatar.jpeg
    - assets/img/argon-logo.png
    - assets/img/argon-logo-onboarding.png
    - assets/img/teacher.png
    - assets/img/main_bottom.png
    - assets/img/main_top.png
    - assets/icons/facebook.svg
    - assets/icons/google-plus.svg
    - assets/icons/login.svg
    - assets/icons/signup.svg
    - assets/icons/twitter.svg
    - assets/img/login_bottom.png
    - assets/img/signup_top.png
    - assets/img/chat2.png
    - assets/img/blackboard.png
    - assets/loading.flr
    - assets/line.png
    - assets/drive-steering-wheel.jpg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600